import { useSelector } from 'react-redux';

import { RootState } from '../redux/store';
import { Theme } from '../redux/slices/settingsDataStateSlice';

export const LIGHT_THEME = {
  PRIMARY_COLOR: '#F5F7FA',
  SECONDARY_COLOR: '#E9ECF0',
  SELECTION_COLOR: '#CBCED3',
  PRIMARY_LIGHT: '#FCFDFE',
  POSITIVE_COLOR: '#92E097',
  HOVER_COLOR: '#DFE2E6',
  ICON_HOVER_COLOR: '#F8FAFC',
  DELETE_ICON_HOVER_COLOR: '#FF8080',
  LABEL_L3_COLOR: '#9A9C9F',
  LABEL_L1_COLOR: '#4A4C4F',
  LABEL_L2_COLOR: '#6E7073',
  TAG_BG_COLOR: '#F0F2F5',
  TAG_BORDER_COLOR: '#DCDEE1',
  BORDER_COLOR: '#4E5053',
  TEXT_COLOR: '#3B3D40',
  SCROLLBAR_TRACK: '#DFE2E6',
  SCROLLBAR_THUMB: '#E7EAF0',
  SCROLLBAR_THUMB_HOVER: '#D8DBDF',
  CONTRAST_COLOR: '#373942',
};

export const WARM_LIGHT_THEME = {
  PRIMARY_COLOR: '#F8F3E8',
  SECONDARY_COLOR: '#EDE8D0',
  SELECTION_COLOR: '#E0DBBF',
  PRIMARY_LIGHT: '#FBF8EF',
  POSITIVE_COLOR: '#7EB37E',
  HOVER_COLOR: '#E9E5D8',
  ICON_HOVER_COLOR: '#F8F6EC',
  DELETE_ICON_HOVER_COLOR: '#FF8C8C',
  LABEL_L3_COLOR: '#7B776F',
  LABEL_L1_COLOR: '#504D41',
  LABEL_L2_COLOR: '#6D6A60',
  TAG_BG_COLOR: '#F5F2E4',
  TAG_BORDER_COLOR: '#E6E2CA',
  BORDER_COLOR: '#D6D2B0',
  TEXT_COLOR: '#28251F',
  SCROLLBAR_TRACK: '#EDE8D0',
  SCROLLBAR_THUMB: '#E0DBBF',
  SCROLLBAR_THUMB_HOVER: '#D8D3B5',
  CONTRAST_COLOR: '#FBFAE8',
};

export const BB_PINK_THEME = {
  PRIMARY_COLOR: '#FAD2E1',
  SECONDARY_COLOR: '#F9BFD2',
  SELECTION_COLOR: '#F89CB9',
  PRIMARY_LIGHT: '#FCE4EC',
  POSITIVE_COLOR: '#F06292',
  HOVER_COLOR: '#F7B3D0',
  ICON_HOVER_COLOR: '#F48FB1',
  DELETE_ICON_HOVER_COLOR: '#FF5252',
  LABEL_L3_COLOR: '#BF4080',
  LABEL_L1_COLOR: '#2A2A2A',
  LABEL_L2_COLOR: '#D81B60',
  TAG_BG_COLOR: '#FCE4EC',
  TAG_BORDER_COLOR: '#F89CB9',
  BORDER_COLOR: '#F48FB1',
  TEXT_COLOR: '#2A2A2A',
  SCROLLBAR_TRACK: '#F9BFD2',
  SCROLLBAR_THUMB: '#F89CB9',
  SCROLLBAR_THUMB_HOVER: '#F06292',
  CONTRAST_COLOR: '#F06292',
};

export const DARKENHEIMER_THEME = {
  PRIMARY_COLOR: '#2A2A2A',
  SECONDARY_COLOR: '#333333',
  SELECTION_COLOR: '#3B3B3B',
  PRIMARY_LIGHT: '#444444',
  POSITIVE_COLOR: '#AF4C7E',
  HOVER_COLOR: '#3E3E3E',
  ICON_HOVER_COLOR: '#4A4A4A',
  DELETE_ICON_HOVER_COLOR: '#E57373',
  LABEL_L3_COLOR: '#6B6B6B',
  LABEL_L1_COLOR: '#B0B0B0',
  LABEL_L2_COLOR: '#8D8D8D',
  TAG_BG_COLOR: '#3E3E3E',
  TAG_BORDER_COLOR: '#2A2A2A',
  BORDER_COLOR: '#4E4E4E',
  TEXT_COLOR: '#D0D0D0',
  SCROLLBAR_TRACK: '#2A2A2A',
  SCROLLBAR_THUMB: '#3B3B3B',
  SCROLLBAR_THUMB_HOVER: '#444444',
  CONTRAST_COLOR: '#1A1A1A',
};

export const BLUE_THEME = {
  PRIMARY_COLOR: '#2A2A3A',
  SECONDARY_COLOR: '#333340',
  SELECTION_COLOR: '#3B3B4A',
  PRIMARY_LIGHT: '#444454',
  POSITIVE_COLOR: '#4C7EAF',
  HOVER_COLOR: '#3E3E48',
  ICON_HOVER_COLOR: '#4A4A58',
  DELETE_ICON_HOVER_COLOR: '#E5739A',
  LABEL_L3_COLOR: '#6B6B7B',
  LABEL_L1_COLOR: '#B0B0BF',
  LABEL_L2_COLOR: '#8D8D9D',
  TAG_BG_COLOR: '#3E3E48',
  TAG_BORDER_COLOR: '#2A2A3A',
  BORDER_COLOR: '#4E4E5E',
  TEXT_COLOR: '#D0D0DF',
  SCROLLBAR_TRACK: '#2A2A3A',
  SCROLLBAR_THUMB: '#3B3B4A',
  SCROLLBAR_THUMB_HOVER: '#444454',
  CONTRAST_COLOR: '#1A1A2A',
};

export function useThemeColors() {
  const settingsData = useSelector(
    (state: RootState) => state.settingsDataState
  );

  if (settingsData.theme === Theme.LIGHT) {
    return LIGHT_THEME;
  } else if (settingsData.theme === Theme.BLUE) {
    return BLUE_THEME;
  } else if (settingsData.theme === Theme.BB_PINK) {
    return BB_PINK_THEME;
  } else if (settingsData.theme === Theme.DARKENHEIMER) {
    return DARKENHEIMER_THEME;
  } else if (settingsData.theme === Theme.WARM_LIGHT) {
    return WARM_LIGHT_THEME;
  }

  return LIGHT_THEME;
}
