// App.tsx
export const GLOBAL = {
  PRIMARY_COLOR: "#E0E0E0",
  SECONDARY_COLOR: "#CACACA",
  SELECTION_COLOR: "#A8A8A8",
  HOVER_COLOR: "#CACACA",
  ICON_HOVER_COLOR: "#FFFFFF",
  DELETE_ICON_HOVER_COLOR: "#FF5733",
};
