// KAN-215. Every icon name the extension can render, as a closed set.
//
// The icon font ships inside the extension as a SUBSET containing only these
// ligatures (src/assets/fonts/, regenerated by `npm run icons:fetch`), about
// 5 KB instead of the full 344 KB. A ligature missing from the subset does not
// render tofu -- it renders its NAME as text, the failure KAN-215 measured
// offline. So the set has to be exactly what the code uses, and a grep cannot
// produce it: names arrive through ternaries, template literals and props.
//
// Hence a type rather than a list to remember. Icon's `type`, Button's
// `iconType` and OverflowMenu's icons all take an IconName, so using a name
// that is not here fails `tsc`. Adding one here without rerunning the fetch
// fails e2e/icon-font-subset.spec.ts, which draws every entry with the bundled
// font.

/** Drawn by the bundled Material Symbols subset. Keep sorted. */
export const LIGATURE_ICON_NAMES = [
  'add_box',
  'add',
  'arrow_back',
  'check',
  'check_circle',
  'cloud_done',
  'cloud_off',
  'cloud_sync',
  'dark_mode',
  'delete',
  'done',
  'download',
  'edit',
  'expand_less',
  'expand_more',
  'filter_center_focus',
  'get_app',
  'globe',
  'history',
  'ios_share',
  'label_off',
  'library_add',
  'light_mode',
  'link',
  'mail',
  'more_vert',
  'playlist_add',
  'print',
  'publish',
  'redo',
  'reopen_window',
  'schedule',
  'search',
  'settings',
  'sort',
  'sort_by_alpha',
  'sync',
  'sync_problem',
  'tab',
  'thumb_up',
  'undo',
  'unfold_less',
  'unfold_more',
  'visibility',
  'visibility_off',
  'web_asset',
] as const;

/** Drawn as inline SVG by Icon's BRAND_GLYPHS; Material Symbols has no logos. */
export const BRAND_ICON_NAMES = ['x', 'tab_keeper'] as const;

export type LigatureIconName = (typeof LIGATURE_ICON_NAMES)[number];
export type BrandIconName = (typeof BRAND_ICON_NAMES)[number];
export type IconName = LigatureIconName | BrandIconName;
