name: Build before merge - tab-keeper-react-chrome-extension

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build before merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test

      - name: Generate dist folder
        run: npm run build
